language: csharp

os:
  - osx
  - linux

# Ubuntu 14.04
sudo: required
dist: xenial

# OS X 10.13
osx_image: xcode9.4

mono:
  - latest

dotnet: 3.1.112

install:
  # workaround for missing .net 4.5 targeting pack
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/

before_install:
  - git fetch --unshallow # Travis always does a shallow clone, but GitVersion needs the full history including branches and tags
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch origin
  - chmod +x build.sh

script:
  - ./build.sh --target Travis --verbosity diagnostic
  
cache:
  directories:
   - tools/Addins
