language: csharp

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
            - dotnet-sdk-3.1

    - os: osx
      osx_image: xcode12.2
      before_install:
        - brew tap homebrew/cask
        - brew install --cask powershell
        - brew tap isen-ng/dotnet-sdk-versions
        - brew install --cask dotnet-sdk3-1-400

  fast_finish: true

mono:
  - latest

dotnet: 5.0.103

before_install:
  - git fetch --unshallow # Travis always does a shallow clone, but GitVersion needs the full history including branches and tags
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch origin
  - chmod +x build.sh

script:
  - ./build.sh --target Travis --verbosity diagnostic

cache:
  directories:
    - tools/Addins
