//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Cake Powershell")]
[assembly: AssemblyVersion("0.1.7")]
[assembly: AssemblyFileVersion("0.1.7")]
[assembly: AssemblyInformationalVersion("0.1.7")]
[assembly: AssemblyCopyright("Copyright (c) Phillip Sharpe 2015")]

